### PR TITLE
Add `make cqa` to standard test/report workflow

### PR DESCRIPTION
**Pull request by dylan-myome**

### CODE REVIEW

**Review by alavertu — APPROVED** [review]
lgtm!

**Review by bwinnacott — APPROVED** [review]
lgtm

**Comment by dylan-myome** [comment]
> We'll just need to make sure we update the Makefiles of the packages using this workflow accordingly.

Yes, that's a next step!

**Review by reece — APPROVED** [review]
ltatm
(Looks totally awesome to me)

**Comment by reece** [comment]
@dylan-myome : Please merge when ready.

**Pull request merged**
