### PR TITLE
Sc 4741/update action to deploy nextflow workflow

### PR DESCRIPTION
**Pull request by bwinnacott**

### CODE REVIEW

**Review by alavertu — APPROVED** [review]
lgtm, like the new dockerfile name/repo

**Comment by alavertu** [comment]
@bwinnacott, thinking about it just now I think we could generalize this to everything we need to ship to EFS. Static-data is shipped the same as this just with a different subdirectory. Thoughts on adding an argument specifying the subdirectory then we can reuse this across multiple repo types?

**Comment by alavertu** [comment]
These Makefile for deploys are essentially the same as this one: 
https://github.com/myome/static-data/blob/main/Makefile
https://github.com/myome/schemas/blob/main/Makefile

**Comment by bwinnacott** [comment]
@alavertu We could we'd just have to be fine with mounting each efs path we need from the shr efs on the runner instance.

**Comment by alavertu** [comment]
@bwinnacott , Sorry, I see. If we can't specify mounts when we call this action, then I prefer this implementation. Can you create the companion versions for the other repos here as well?

**Comment by bwinnacott** [comment]
@alavertu Updated action to include logic for handling all shr efs deployments. Commented out the schemas deployment for now due to the symlink situation.

**Pull request merged**
